### ISSUE TITLE
Incorrect receipt of offsets

### ISSUE THREAD

**Issue by maxrskiy** [dhanax26/Apex-Legends-Offset-Dumper#3]
Your dumper does not receive the viewmatrix offset correctly, you can check it yourself

**Comment by dhanax26** [comment]
Hi, the viewmatrix provided by this dumper dones't need to be added to the viewrender address. You just need to do GameBase + ViewMatrix and all should be fine.

https://github.com/dhanax26/Apex-Legends-Offset-Dumper/blob/main/Apex%20Offsets%20Dumper/Dumper/Dumper.hpp#L232
