### ISSUE TITLE
LastVisibleTime

### ISSUE THREAD

**Issue by ch4ncellor** [dhanax26/Apex-Legends-Offset-Dumper#4]
In your tool, LastVisibleTime signature is outdated: https://github.com/dhanax26/Apex-Legends-Offset-Dumper/blob/8e91f96e7f67b27cd92bd7eae6922613874c7b85/Apex%20Offsets%20Dumper/Dumper/Dumper.hpp#L268

This is the most recent signature for r5apex
`\x8B\x8F\xD4\x1A\x00\x00 : xxxxxx `
![](https://i.imgur.com/XQpmUpE.png)

**Comment by dhanax26** [comment]
True, thank you, i updated it.
